In [1284]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np

In [1285]:
# horizntal cell in this matrix... first 2 columns are position. 0,0; 0,1 etc. 
# third position is wheter blocked (0) or open (1).
# fourth position is index of whether / when visited. 0 means not visited yet. a number would indicate nth step.
# total N * M tiles. blocked n * m. N,n - vertical. M,m - horizontal 
# N(i) -> x.   M(j) -> y 
N = 4
M = 3
n = 0
m = 0

arr = np.empty((N,M,4)).astype(np.int32)

for i in range(N):
    for j in range(M):
        arr[i,j] = [i,j,1,0]

arr[0:n,0:m,2] = 0
arr[N-n:N,M-m:M,2] = 0
arr[0:n,M-m:M,2] = 0
arr[N-n:N,0:m,2] = 0

In [1286]:
step = 1
total_steps = 0
for i in range(N):
    for j in range(M):
        if (total_steps == 0):
            if (arr[i,j,2] == 1) & (arr[i,j,3] == 0):
                arr[i,j,3] = step
                x = i
                y = j
                current_process = 'x+1'
        if (arr[i,j,2] == 1):
            total_steps = total_steps + 1
print(x,y, total_steps, arr[x,y])  


0 0 12 [0 0 1 1]


In [1287]:
for step in range(2, total_steps+1):
    if current_process == 'x+1':
        if (y-1 >= 0):
            if (arr[x,y-1,2] == 1) & (arr[x,y-1,3] == 0):
                arr[x,y-1,3] = step
                y = y-1
                current_process = 'y-1'
        elif (x+1 < N):
            if (arr[x+1,y,2] == 1) & (arr[x+1,y,3] == 0):
                arr[x+1,y,3] = step
                x = x+1
                current_process = 'x+1'
        elif (y+1 < M):
            if (arr[x,y+1,2] == 1) & (arr[x,y+1,3] == 0):
                arr[x,y+1,3] = step
                y = y+1
                current_process = 'y+1'
    elif current_process == 'y+1':
        if (x+1 < N):
            if (arr[x+1,y,2] == 1) & (arr[x+1,y,3] == 0):
                arr[x+1,y,3] = step
                x = x+1
                current_process = 'x+1'
        elif (y+1 < M):
            if (arr[x,y+1,2] == 1) & (arr[x,y+1,3] == 0):
                arr[x,y+1,3] = step
                y = y+1
                current_process = 'y+1'
        elif (x-1 >= 0):
            if (arr[x-1,y,2] == 1) & (arr[x-1,y,3] == 0):
                arr[x-1,y,3] = step
                x = x-1
                current_process = 'x-1'
    elif current_process == 'x-1':
        if (y+1 < M):
            if (arr[x,y+1,2] == 1) & (arr[x,y+1,3] == 0):
                arr[x,y+1,3] = step
                y = y+1
                current_process = 'y+1'
        elif (x-1 >= 0):
            if (arr[x-1,y,2] == 1) & (arr[x-1,y,3] == 0):
                arr[x-1,y,3] = step
                x = x-1
                current_process = 'x-1'
        elif (y-1 >= 0):
            if (arr[x,y-1,2] == 1) & (arr[x,y-1,3] == 0):
                arr[x,y-1,3] = step
                y = y-1
                current_process = 'y-1'
    elif current_process == 'y-1':
        if (x-1 >= 0):
            if (arr[x-1,y,2] == 1) & (arr[x-1,y,3] == 0):
                arr[x-1,y,3] = step
                x = x-1
                current_process = 'x-1'
        elif (y-1 >= 0) & (arr[x,y-1,2] == 1) & (arr[x,y-1,3] == 0):
                arr[x,y-1,3] = step
                y = y-1
                current_process = 'y-1'
        elif (x+1 < N) & (arr[x+1,y,2] == 1) & (arr[x+1,y,3] == 0):
                arr[x+1,y,3] = step
                x = x+1
                current_process = 'x+1'
            
    print(current_process,x,y,step,arr[x,y])


x+1 1 0 2 [1 0 1 2]
x+1 2 0 3 [2 0 1 3]
x+1 3 0 4 [3 0 1 4]
y+1 3 1 5 [3 1 1 5]
y+1 3 2 6 [3 2 1 6]
x-1 2 2 7 [2 2 1 7]
x-1 1 2 8 [1 2 1 8]
x-1 0 2 9 [0 2 1 9]
y-1 0 1 10 [ 0  1  1 10]
x+1 1 1 11 [ 1  1  1 11]
x+1 1 1 12 [ 1  1  1 11]


In [1270]:
arr

array([[[ 0,  0,  1,  1],
        [ 0,  1,  1, 10],
        [ 0,  2,  1,  9]],

       [[ 1,  0,  1,  2],
        [ 1,  1,  1, 11],
        [ 1,  2,  1,  8]],

       [[ 2,  0,  1,  3],
        [ 2,  1,  1,  0],
        [ 2,  2,  1,  7]],

       [[ 3,  0,  1,  4],
        [ 3,  1,  1,  5],
        [ 3,  2,  1,  6]]])

In [1235]:
for i in range(N):
    for j in range(M):
        if (arr[i,j,2] == 1):
            if (arr[i,j,3] != 0):
                print (arr[i,j], 'was open -- now USED --')
            else:
                print (arr[i,j], 'open')
        else:
            print (arr[i,j], 'blocked')


[0 0 1 1] was open -- now USED --
[ 0  1  1 18] was open -- now USED --
[ 0  2  1 17] was open -- now USED --
[ 0  3  1 16] was open -- now USED --
[ 0  4  1 15] was open -- now USED --
[1 0 1 2] was open -- now USED --
[1 1 1 0] open
[1 2 1 0] open
[1 3 1 0] open
[ 1  4  1 14] was open -- now USED --
[2 0 1 3] was open -- now USED --
[2 1 1 0] open
[2 2 1 0] open
[2 3 1 0] open
[ 2  4  1 13] was open -- now USED --
[3 0 1 4] was open -- now USED --
[3 1 1 0] open
[3 2 1 0] open
[3 3 1 0] open
[ 3  4  1 12] was open -- now USED --
[4 0 1 5] was open -- now USED --
[4 1 1 0] open
[4 2 1 0] open
[4 3 1 0] open
[ 4  4  1 11] was open -- now USED --
[5 0 1 6] was open -- now USED --
[5 1 1 7] was open -- now USED --
[5 2 1 8] was open -- now USED --
[5 3 1 9] was open -- now USED --
[ 5  4  1 10] was open -- now USED --
